@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjEsImlhdCI6MTcyMzk1Mzg2OCwiZXhwIjoxNzI0MDQwMjY4fQ.652I6j8Umj7v5eYxOk4WUa2YxRYHAmnmsZ4riWj64T8

### All Recipes Index Action
GET http://localhost:3000/allrecipes

### All Ingredients Index Action
GET http://localhost:3000/ingredients

### All Cooking Styles Index Action
GET http://localhost:3000/cookingstyles

### User Recipes Index Action
GET http://localhost:3000/recipes

### User Recipes Create Action
POST http://localhost:3000/recipes
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "user_id": 1
}

### User Signup
POST http://localhost:3000/signup
Content-Type: application/json

{
  "name": "username6",
  "password": "password2"
}

### User Login
GET http://localhost:3000/login
Content-Type: application/json

{
  "name": "username6",
  "password": "password2"
}