### All Recipes Index Action
GET http://localhost:3000/allrecipes

### All Ingredients Index Action
GET http://localhost:3000/ingredients

### All Cooking Styles Index Action
GET http://localhost:3000/cookingstyles

### User Recipes Index Action
GET http://localhost:3000/recipes

### User Recipes Create Action
POST http://localhost:3000/recipes
Content-Type: application/json

{
  "name": "fish",
  "cooking_time": 3,
  "steps": "something something"
}

### User Signup
POST http://localhost:3000/signup
Content-Type: application/json

{
  "name": "username6",
  "password": "password2"
}

### User Login
GET http://localhost:3000/login
Content-Type: application/json

{
  "name": "username6",
  "password": "password2"
}