### Recipes Index Action
GET http://localhost:3000/recipes

### Recipes Create Action
POST http://localhost:3000/recipes
Content-Type: application/json

{
  "name": "fish",
  "cooking_time": 3,
  "steps": "something something"
}

### User Index Action
GET http://localhost:3000/users/2

### User Create Action
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "username 2",
  "pasword": "password"
}

### User Signup
POST http://localhost:3000/signup
Content-Type: application/json

{
  "name": "username 3",
  "password": "password"
}

### User Login